version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: wb
    ports:
      - "5436:5432"
  nats-streaming:
    image: nats-streaming
    container_name: my_nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"